sudo: required
services:
  - docker

before_install:
  - docker build -t steelersd/react-test -f  ./client/Dockerfile.dev ./client

script:
  - docker run steelersd/react-test npm test -- --coverage

after_success:
  - docker build -t steelersd/multi-client ./client
  - docker build -t steelersd/multi-nginx ./nginx
  - docker build -t steelersd/multi-server ./server
  - docker build -t steelersd/multi-worker ./worker

  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_ID" --password-stdin

  # Push images to Docker Hub
  - docker push steelersd/multi-client
  - docker push steelersd/multi-nginx
  - docker push steelersd/multi-server
  - docker push steelersd/multi-worker

deploy:
  provider: elasticbeanstock
  region: us-east-2
  app: multi-docker
  env: MultiDocker-env
  bucket_name: elasticbeanstalk-us-east-2-854836931922
  bucket_path: docker-multi # looks like this is arbitrary
  on:
    branch: master
  access_key_id: $AWS_ACCESS_KEY
  secret_access_key:
    secure: $AWS_SECRET_KEY
